### ISSUE TITLE
PKG seems to be built in unexpected way

### ISSUE THREAD

**Issue by secondfry** [amiantos/lifesaver#20]
While trying to unpack `lifesaver-1.1.pkg` I'm getting following error:
```
% pkgutil --expand lifesaver-1.1.pkg ./lifesaver
pkgutil(37305,0x11926a5c0) malloc: can't allocate region
*** mach_vm_map(size=255086697644032) failed (error code=3)
pkgutil(37305,0x11926a5c0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    37305 abort      pkgutil --expand lifesaver-1.1.pkg ./lifesaver
```

Sometime you run in environment there you can't provide administrator user and password. For such environments you would use `screensaver name.saver` file to install it only for local user. This is I'm trying to unpack your wallpaper.

**Comment by amiantos** [comment]
The pkg is an installer, I don't think you can just unpack it...? I admit, I put it in an installer because I didn't know how to sign the `.saver`, which I do now, so I can look into offering the raw saver download.

**Comment by secondfry** [comment]
Well, technically every installer is an archive and a piece of code which unpacks said archive.
`pkgutil` man page states: "Query and manipulate Mac OS X Installer packages and receipts.". I guess there is a chance they have bug in their own tool as installer works properly as GUI application...

**Comment by amiantos** [comment]
New release of the screensaver comes in a simple zip file, so hopefully this will no longer be an issue for anyone. Closing...

https://github.com/amiantos/lifesaver/releases/tag/v1.2
