### ISSUE TITLE
Does not work with MacOS 12.2.1

### ISSUE THREAD

**Issue by jsfr** [amiantos/lifesaver#21]
After the latests upgrade to MacOS 12.2.1, Lifesaver no longer works and instead gives a messages as screensaver that this screensaver doesn't work with this version of MacOS and to please contact the author.

Unsure if this is relevant too (and unable to check), I am running an M1 chip.

**Comment by amiantos** [comment]
This error seems to happen with macOS and will eventually go away/stop happening, but I don't know what the magic words or actions are to get it to stop happening. Have you tried deleting it (right click on it in the screensavers panel to show in finder), closing settings, then reinstalling it?

**Comment by jsfr** [comment]
yeah it worked to uninstall and reinstall again 🤷. I'll close this again
